### DISCUSSION TITLE
Plugin Supercharged Links

### DISCUSSION THREAD

**Discussion by D7891** [BryanJenksCommunity/FAQ#101] [Q&A] [answered]
Hi Bryan,  can you tell me how are your settings for the supercharged links plugin or where can I find a good explanation? I am a pianist, not a programmer. I really do like the visual effect that this feature brings in the timeline note. thank you!🤓

**Comment by tallguyjenks** [comment, marked as answer]
Supercharged links settings:

in obsidian:

![image](https://user-images.githubusercontent.com/29872822/128650192-e56a6a26-9596-41fd-9a99-73b465caca4a.png)


and this in my CSS file:

```css
/** ________ 2.9.3 Input Links -- https://discord.com/channels/686053708261228577/707816848615407697/844751423253905458 */
a.internal-link[data-link-type$="video" i]::before{
  content: "🎥 "attr(data-link-status)" "
}
a.internal-link[data-link-type$="article" i]::before{
  content: "📰️ "attr(data-link-status)" "
}
a.internal-link[data-link-type$="book" i]::before{
  content: "📚 "attr(data-link-status)" "
}
a.internal-link[data-link-type$="paper" i]::before{
  content: "📜️ "attr(data-link-status)" "
}
a.internal-link[data-link-type$="podcast" i]::before{
  content: "🎧️ "attr(data-link-status)" "
}
a.internal-link[data-link-type$="tweet" i]::before{
  content: "🐦️ "attr(data-link-status)" "
}
a.internal-link[data-link-type$="thought" i]::before{
  content: "💭️ "attr(data-link-status)" "
}
```
