### DISCUSSION TITLE
how do you colour the non-existent file/link node in graphs as red?

### DISCUSSION THREAD

**Discussion by loneguardian** [BryanJenksCommunity/FAQ#167] [Q&A] [answered]
hi, I am wondering how do you colour the non-existent links in graph as red? Can't seem to figure out a search that matches non-existent links.

**Comment by tallguyjenks** [comment, marked as answer]
in my CSS file is the code to apply some theme-ing programmatically:

```css
/** ____ 2.5 Graph Formatting */
/** ______ 2.5.1 Graph View CSS -- https://discordapp.com/channels/686053708261228577/702656734631821413/760488978691784705 */
.theme-dark .graph-view.color-arrow {
  color: var(--bright-aqua);
}
.theme-dark .graph-view.color-fill-tag {
  color: var(--bright-yellow);
}
.theme-dark .graph-view.color-fill-attachment {
  color: var(--neutral-blue);
}
.theme-dark .graph-view.color-fill-unresolved {
  color: var(--bright-red);
}
.graph-view.color-fill-focused {
  color: var(--faded-red);
}
.graph-view.color-fill {
  color: var(--light1);
}
/* .graph-view.color-line {
  color: var(--gray);
}*/
```
