### DISCUSSION TITLE
How do you make your headings like in your Obsidian publish notes?

### DISCUSSION THREAD

**Discussion by nphalem** [BryanJenksCommunity/FAQ#168] [Q&A] [answered]
I downloaded your starter vault and used your theme but I'm wondering how do you get that green lines in headings.

**Comment by tallguyjenks** [comment]
what green lines? the theme available in the most up to date. if you're talking about older videos and the styles there, i likely no longer have/use the code for that. it may be in the CSS file commented out

**Reply by nphalem** [reply]
When you open INDEX on this site https://publish.obsidian.md/bryan-jenks/Z/INDEX you should see that heading is centered and there are green lines around it. I downloaded your latest template but I don't have headings like that.

**Reply by tallguyjenks** [reply, marked as answer]
oh, thats my old CSS, i havent updated the CSS on the publish site in ages.. i should do that today. 

i think what you're looking for is this:

```css
/** ........ 2.11.3 Heading Horizontal Lines -- https://forum.obsidian.md/t/meta-post-common-css-hacks/1978/288?u=tallguyjenks */
h1,h2,h3,h4,h5,h6 {
	display: flex;
	width: 100%;
	align-items: center;
}
h1:before, h1:after, 
h2:before, h2:after, 
h3:before, h3:after, 
h4:before, h4:after, 
h5:before, h5:after, 
h6:before, h6:after {
	content: '';
	background: var(--bright-aqua);
	height: .1em;
	margin: .2em;
	flex: 1;
}
```
