### DISCUSSION TITLE
Obsidian title bar color sheme

### DISCUSSION THREAD

**Discussion by spandankeshav** [BryanJenksCommunity/FAQ#174] [Q&A] [answered]
Hello,

I recently saw in Bryan's obsidian that the title bar has some color scheme. Just wondering whether it comes with some plugins ro need to modify css? Attached you will see what I was meaning. Thanks a lot for your help in advance!

Cheers!
<img width="358" alt="Screenshot 2023-05-27 at 13 09 14" src="https://github.com/BryanJenksCommunity/FAQ/assets/17289501/8e41958d-8fd3-4093-83af-10df8091b412">

**Comment by tallguyjenks** [comment, marked as answer]
its just CSS targeting the icon itself

```css
.lucide-bookmark {
  color: var(--neutral-blue);
  fill: var(--neutral-blue);
}
.lucide-hash {
  color: var(--neutral-orange);
}
.lucide-search, .lucide-git-fork, .lucide-file {
  color: var(--light1);
}
.lucide-folder-closed {
  color: var(--neutral-yellow);
}
.lucide-clock {
  color: var(--neutral-aqua);
}
.lucide-calendar-check {
  color: var(--bright-red);
}
```
