### DISCUSSION TITLE
How do i get this Gruvbox font in Anki?

### DISCUSSION THREAD

**Discussion by LuiZzz-Menezes** [BryanJenksCommunity/FAQ#45] [Q&A] [answered]
Could you share how to change the font of Anki and if it's imported from Obsidian, how to can i do?

**Comment by tallguyjenks** [comment, marked as answer]
this is a distinction, do you really mean the font? or the gruvbox color scheme? these are 2 mutually exclusive things

**Reply by LuiZzz-Menezes** [reply]
I mean, the gruvbox color scheme, but if its only for Anki.

**Reply by tallguyjenks** [reply]
okay, yes, the gruvbox styling is from me editing the card template CSS, for instance, my Basic card template has the following CSS:

```css
.card {
  font-family: fira code;
  font-size: 20px;
  text-align: center;
  color: #ebdbb2 !important;
  background-color: #282828 !important;
}
#spacer, #answer {
background-image: linear-gradient(to right, #282828, #d65d0e, #282828);
}

#spacer, #answer {
  margin-block-start: 4em;
  margin-block-end: 4em;
  border: none;
  height: 1px;
}

#spacer::after, #answer::after {
  content: 'ᛟ';
  display: inline-block;
  position: absolute;
  left: 50%;
  transform: translate(-50%, -50%) rotate(0deg);
  transform-origin: 50% 50%;
  padding: 0.5rem;
  color: #689d6a;
  background-color: #282828;
}
```

which gives this appearance:

|||
|---|---|
|![image](https://user-images.githubusercontent.com/29872822/111092966-da0b6a80-84f4-11eb-9a1a-a2c19948a77b.png)|![image](https://user-images.githubusercontent.com/29872822/111092982-e7c0f000-84f4-11eb-9ed5-4983c3c8a65e.png)|
