### DISCUSSION TITLE
Managing [[tags]] and their development to MOCs

### DISCUSSION THREAD

**Discussion by Dalnorae** [BryanJenksCommunity/FAQ#49] [Q&A] [answered]
Hello Bryan!

I’m loving the Obsidian content you put out. Although they were overwhelming at first, I began to appreciate how you managed your Vault! I’m still in my early stages of filling out my vault, but I wanted to have a firm system in place for the future. And your [[tag]] -> MOC system was mind blowing.

But as I fiddled around with my notes, I had some questions regarding some aspects of the [[tag]] system.

1. do you restrain yourself when [[tagging]]? or do you [[tag]] whatever subject it may relate to for future proofing and etc. I ask because I feel like the overwhelming lines on the graph view could be distracting in the long run.
2. when you develop a profusely [[tagged]] note (let’s say Productivity) into an MOC, do you change the name of it to a Productivity MOC? If so, do you connect [[productivity]] tags to the MOC or do you starting building up the [[productivity]] note anew? Or does it become a top-down approach once you have an MOC in place?
3. how do you make your profusely connected nodes bigger? is it a css thing you are using? or do i need to connect more nodes to see changes?
4. finally, is there any easy way to change node colors? I’m slightly colorblind and most of the themes online are not really helpful.

Thanks! I apologize if any of these have been answered elsewhere.

**Comment by tallguyjenks** [comment, marked as answer]
1. i tag liberally, and if i want to ignore the "noise" of the [[tags]] on the graph I can just toggle the option to remove files that don't exist
2. [[productivity]] will then just exist as a note with some content in it and links to some of the notes that are tagged [[productivity]] i also include my tag for MOCS  #🗺️ so that helps me filter down to just MOCS on the graph
3. it's the normal graph behavior, more links = larger node
4. yes! there's CSS to do it:

```css
/* ...... 2.5.1 Graph View CSS -- https://discordapp.com/channels/686053708261228577/702656734631821413/760488978691784705 */
.theme-dark .graph-view.color-arrow {
  color: var(--bright-aqua);
}
.theme-dark .graph-view.color-fill-tag {
  color: var(--bright-yellow);
}
.theme-dark .graph-view.color-fill-attachment {
  color: var(--neutral-blue);
}
.theme-dark .graph-view.color-fill-unresolved {
  color: var(--bright-red);
}
.graph-view.color-fill {
  color: var(--light1);
}
```
