### DISCUSSION TITLE
Styling for Anki

### DISCUSSION THREAD

**Discussion by ThomasOctavian** [BryanJenksCommunity/FAQ#99] [Q&A] [answered]
Hello Bryan and Community, 

I'm currently in the middle of your video 'Best Ways to Learn Javascript with Anki & Obsidian'; at around the 5 minute mark you advised your viewers post here if we're interested in getting our hands on the styling you have set in Anki. I'd love to get my hands on it when you find the time.

Love what you do, let me know if you can help.

**Comment by tallguyjenks** [comment, marked as answer]
sure! here's the Anki CSS behind my cards for 

<details>
<summary>basic</summary>

```css
.card {
  font-family: fira code;
  font-size: 20px;
  text-align: center;
  color: #ebdbb2 !important;
  background-color: #282828 !important;
}
#spacer, #answer {
background-image: linear-gradient(to right, #282828, #d65d0e, #282828);
}

#spacer, #answer {
  margin-block-start: 4em;
  margin-block-end: 4em;
  border: none;
  height: 1px;
}

#spacer::after, #answer::after {
  content: 'ᛟ';
  display: inline-block;
  position: absolute;
  left: 50%;
  transform: translate(-50%, -50%) rotate(0deg);
  transform-origin: 50% 50%;
  padding: 0.5rem;
  color: #689d6a;
  background-color: #282828;
}
```

</details>



<details>
<summary>close deletion</summary>

```css
.cloze {
 font-weight: bold;
 color: #076678;
}
.nightMode .cloze {
 color: #458588;
}
.card {
  font-family: fira code;
  font-size: 20px;
  text-align: center;
  color: #ebdbb2 !important;
  background-color: #282828 !important;
}
#spacer, #answer {
background-image: linear-gradient(to right, #282828, #d65d0e, #282828);
}

#spacer, #answer {
  margin-block-start: 4em;
  margin-block-end: 4em;
  border: none;
  height: 1px;
}

#spacer::after, #answer::after {
  content: 'ᛟ';
  display: inline-block;
  position: absolute;
  left: 50%;
  transform: translate(-50%, -50%) rotate(0deg);
  transform-origin: 50% 50%;
  padding: 0.5rem;
  color: #689d6a;
  background-color: #282828;
}
```

</details>

<details>
<summary>Programming Typing Cards</summary>

```css
.card {
  font-family: fira code;
  font-size: 20px;
  text-align: center;
  color: #ebdbb2 !important;
  background-color: #282828 !important;
}
#spacer, #answer {
background-image: linear-gradient(to right, #282828, #d65d0e, #282828);
}

#spacer, #answer {
  margin-block-start: 4em;
  margin-block-end: 4em;
  border: none;
  height: 1px;
}

#spacer::after, #answer::after {
  content: 'ᛟ';
  display: inline-block;
  position: absolute;
  left: 50%;
  transform: translate(-50%, -50%) rotate(0deg);
  transform-origin: 50% 50%;
  padding: 0.5rem;
  color: #689d6a;
  background-color: #282828;
}

.typeGood {
  background-color: #427b58;
}
.typeBad {
  background-color: #9d0006;
}
.typeMissed {
  background-color: #928374;
}

a {
  color: #d65d0e !important;
}
strong {
  color: #d79921;
}
```

</details>
